const db = require('./config/db');

(async () => {
    try {
        console.log('=== PAYROLL SETTINGS -> PAYROLL INTELLIGENCE CONNECTION TEST ===\n');

        // 1. Check components
        console.log('1. SALARY COMPONENTS (from Payroll Settings):');
        const c = await db.query("SELECT id, name, type, epf_eligible, etf_eligible, welfare_eligible FROM salary_components WHERE status = 'Active' ORDER BY id");
        c.rows.forEach(r => console.log(`  [${r.id}] ${r.name.padEnd(25)} | ${r.type.padEnd(10)} | EPF:${r.epf_eligible ? 'Y' : 'N'} ETF:${r.etf_eligible ? 'Y' : 'N'} Welfare:${r.welfare_eligible ? 'Y' : 'N'}`));

        // 2. Check structures
        console.log('\n2. EMPLOYEE STRUCTURES (set in Payroll Settings -> Global Compensation Override):');
        const e = await db.query(`
            SELECT es.employee_id, u.name, sc.name as comp, es.amount 
            FROM employee_salary_structure es 
            JOIN salary_components sc ON es.component_id = sc.id 
            JOIN employees emp ON es.employee_id = emp.id 
            JOIN users u ON emp.user_id = u.id 
            ORDER BY es.employee_id, sc.id
        `);
        let currentEmp = null;
        let empTotal = 0;
        e.rows.forEach(r => {
            if (r.employee_id !== currentEmp) {
                if (currentEmp) console.log(`    TOTAL: LKR ${empTotal.toLocaleString()}`);
                currentEmp = r.employee_id;
                empTotal = 0;
                console.log(`  --- Employee ${r.employee_id}: ${r.name.substring(0, 40)} ---`);
            }
            empTotal += parseFloat(r.amount);
            console.log(`    ${r.comp.padEnd(25)}: LKR ${parseFloat(r.amount).toLocaleString()}`);
        });
        if (currentEmp) console.log(`    TOTAL: LKR ${empTotal.toLocaleString()}`);

        // 3. Check payroll records (produced by Payroll Intelligence)
        console.log('\n3. PAYROLL RECORDS (generated by Payroll Intelligence):');
        const p = await db.query(`
            SELECT p.id, u.name, p.basic_salary, p.bonuses, p.deductions, p.net_salary, 
                   p.epf_employee, p.epf_employer, p.etf_employer, p.welfare, p.month, p.status
            FROM payroll p JOIN users u ON p.user_id = u.id ORDER BY p.id
        `);
        if (p.rows.length === 0) {
            console.log('  ⚠ NO PAYROLL RECORDS FOUND');
        } else {
            p.rows.forEach(r => {
                console.log(`  #${r.id} ${r.name.substring(0, 30).padEnd(30)} | ${r.month}`);
                console.log(`     Basic: ${r.basic_salary} | Bonuses: ${r.bonuses} | Deductions: ${r.deductions} | Net: ${r.net_salary}`);
                console.log(`     EPF emp: ${r.epf_employee} | EPF co: ${r.epf_employer} | ETF: ${r.etf_employer} | Welfare: ${r.welfare} | Status: ${r.status}`);
            });
        }

        // 4. Check liabilities
        console.log('\n4. STATUTORY LIABILITIES:');
        const l = await db.query('SELECT * FROM payroll_liabilities ORDER BY id');
        if (l.rows.length === 0) {
            console.log('  ⚠ NO LIABILITIES FOUND');
        } else {
            l.rows.forEach(r => console.log(`  ${r.month.padEnd(12)} | ${r.type.padEnd(8)} | LKR ${Number(r.total_payable).toLocaleString().padStart(10)} | Paid: ${Number(r.paid_amount || 0).toLocaleString().padStart(8)} | Status: ${r.status}`));
        }

        // 5. Cross-check: structure amount vs payroll amount
        console.log('\n5. CROSS-CHECK (Structure vs Payroll):');
        const emps = await db.query(`
            SELECT e.id as emp_id, u.id as user_id, u.name,
                   e.is_epf_eligible, e.is_etf_eligible
            FROM employees e JOIN users u ON e.user_id = u.id ORDER BY e.id
        `);

        for (const emp of emps.rows) {
            const struct = await db.query(`
                SELECT SUM(es.amount) as total, 
                       SUM(CASE WHEN sc.type = 'Earning' THEN es.amount ELSE 0 END) as earnings,
                       SUM(CASE WHEN sc.epf_eligible THEN es.amount ELSE 0 END) as epf_base,
                       SUM(CASE WHEN sc.welfare_eligible THEN es.amount ELSE 0 END) as welfare_base
                FROM employee_salary_structure es
                JOIN salary_components sc ON es.component_id = sc.id
                WHERE es.employee_id = $1
            `, [emp.emp_id]);

            const payroll = await db.query('SELECT * FROM payroll WHERE user_id = $1 LIMIT 1', [emp.user_id]);

            const s = struct.rows[0];
            const structGross = parseFloat(s.earnings || 0);
            const epfBase = parseFloat(s.epf_base || 0);
            const welfareBase = parseFloat(s.welfare_base || 0);
            const expectedEPFemp = emp.is_epf_eligible ? epfBase * 0.08 : 0;
            const expectedEPFco = emp.is_epf_eligible ? epfBase * 0.12 : 0;
            const expectedETF = emp.is_etf_eligible ? epfBase * 0.03 : 0;
            const expectedWelfare = welfareBase * 0.02;

            let status = '✓';
            let issues = [];

            if (payroll.rows.length > 0) {
                const pr = payroll.rows[0];
                const payGross = parseFloat(pr.basic_salary) + parseFloat(pr.bonuses);
                if (Math.abs(payGross - structGross) > 1) issues.push(`Gross: struct=${structGross} vs payroll=${payGross}`);
                if (Math.abs(parseFloat(pr.epf_employee) - expectedEPFemp) > 1) issues.push(`EPF emp: expected=${expectedEPFemp} vs actual=${pr.epf_employee}`);
                if (Math.abs(parseFloat(pr.epf_employer) - expectedEPFco) > 1) issues.push(`EPF co: expected=${expectedEPFco} vs actual=${pr.epf_employer}`);
                if (Math.abs(parseFloat(pr.etf_employer) - expectedETF) > 1) issues.push(`ETF: expected=${expectedETF} vs actual=${pr.etf_employer}`);
                if (Math.abs(parseFloat(pr.welfare) - expectedWelfare) > 1) issues.push(`Welfare: expected=${expectedWelfare} vs actual=${pr.welfare}`);
                if (issues.length > 0) status = '✗ MISMATCH';
            } else {
                status = '⚠ No payroll record';
            }

            console.log(`  ${emp.name.substring(0, 30).padEnd(30)} | EPF:${emp.is_epf_eligible ? 'Y' : 'N'} ETF:${emp.is_etf_eligible ? 'Y' : 'N'} | ${status}`);
            issues.forEach(i => console.log(`    → ${i}`));
        }

        console.log('\n=== TEST COMPLETE ===');

    } catch (e) {
        console.log('Error:', e.message, e.stack);
    } finally {
        process.exit();
    }
})();
